# Generated by Django 4.1 on 2022-10-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='eid',
            new_name='uid',
        ),
    ]
